insert into SECURITY_ROLE values(1, 'ADMIN_ROLE');
insert into SECURITY_ROLE values(2, 'USER_ROLE');
INSERT INTO SECURITY_USER VALUES (1, 'PBKDF2WithHmacSHA256:2048:IsjUIm8gNUJs4FtF0SPv7AiPJrMOglGKl69kutYB3Mk=:GYsuFDp33eRsdcJXqy68ooSxOeObKrfHQZc7gW17Uc4=', 'admin', NULL);
INSERT INTO SECURITY_USER_SECURITY_ROLE values(1,1);
INSERT INTO SECURITY_USER VALUES (2, 'PBKDF2WithHmacSHA256:2048:F7hRhGwAbRCijqcApAiomur+J1zF3gom2CFpqKC+IpQ=:YNec/z7YHsqRXMSR8rDV9Z4XL4AFGEsjvY7jwq31Zmk=', 'user', NULL);
INSERT INTO SECURITY_USER_SECURITY_ROLE values(2,2);